name: BungeeForwardCancelledChat
version: '${version}'
description: "${description}"
authors: [blablubbabc]
website: '${url}'

main: de.blablubbabc.bungeeForwardCancelledChat.spigot.SpigotPlugin
api-version: '1.14'

commands:
    bfcc-s:
      description: 'Base for all BungeeForwardCancelledChat commands.'
      aliases: [BungeeForwardCancelledChat-Spigot]

permissions:
    bfcc.admin:
        description: Access to utility and debugging commands.
        default: op